### PR TITLE
feat(audiobook-tests): Add audiobook unit tests

### LINKED ISSUE #114: Add Audiobooks tests
Currently, audibooks are only available in the US, so I am not able to access any to get the ID and test. If anyone is willing to write tests for the Audiobooks, please comment here and I will assign you.

Take a look at [tests](https://github.com/spotifyts/spotify.ts/tree/main/tests) to familiarize yourself with the code. Then create a similar test for both the manager's functions (`fetch` and `fetchSeveral`)

### PR DESCRIPTION
**Pull request by prashanthr**
Reference Doc: https://developer.spotify.com/documentation/web-api/reference/#/operations/get-multiple-audiobooks

Fixes #114

### CODE REVIEW

**Comment by prashanthr** [comment]
@FC5570 Thanks for fixing the secrets issue with the workflow. I tried running the tests for Audiobook locally using my own secrets and I'm running into a http 500 issue. I'll investigate more and post an update later.

**Comment by FC5570** [comment]
> @FC5570 Thanks for fixing the secrets issue with the workflow. I tried running the tests for Audiobook locally using my own secrets and I'm running into a http 500 issue. I'll investigate more and post an update later.

Oh the secrets are working for you? Weird 🤔. The issue still persists in the action.

**Comment by prashanthr** [comment]
> > @FC5570 Thanks for fixing the secrets issue with the workflow. I tried running the tests for Audiobook locally using my own secrets and I'm running into a http 500 issue. I'll investigate more and post an update later.
> 
> The issue with the workflow hasn't been fixed yet. I'm looking for a solution...

Okay I just tested Audiobooks tests locally with my own secrets and everything is working. The ids on the doc site were wrong so I got some new ids. 

As far as the workflow is concerned, I just tried reordering the values to see if that helps set the secrets first before running. In the meantime will try looking into github docs some more.

**Comment by prashanthr** [comment]
From https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
> For secrets stored at the environment level, you can enable required reviewers to control access to the secrets. A workflow job cannot access environment secrets until approval is granted by required approvers.

Also https://github.com/pypa/gh-action-pypi-publish/discussions/49

It might be an access issue

**Comment by FC5570** [comment]
I'll try to come up with a fix.

**Comment by FC5570** [comment]
Can you try this please @prashanthr https://github.com/actions/starter-workflows/issues/785#issuecomment-863758767

**Comment by prashanthr** [comment]
@FC5570 Just added the quotes back. Go ahead and approve the workflow and we can see if it passes. If it still fails, I'm almost sure it's a permissions issue that I mentioned above using my auth to access secrets.

**Comment by FC5570** [comment]
It failed. I guess we can't do anything else but to only run the tests on push to the main branch and lint and build on the pull request. I'm still confused though... the tests work on another pr made by a bot but not on this one..

**Comment by prashanthr** [comment]
> It failed. I guess we can't do anything else but to only run the tests on push to the main branch and lint and build on the pull request. I'm still confused though... the tests work on another pr made by a bot but not on this one..

@FC5570 I think the reason it works for you is that you have permissions on the secrets but I do not. This discussion I posted above explains a lot about using secrets from a fork.

https://github.com/pypa/gh-action-pypi-publish/discussions/49#discussioncomment-162653

I'll try changing it the workflow to run on a push as a test over pull_request and you can fix it later but if that doesn't work then we might have to merge this and test it out on a follow up PR.

**Comment by FC5570** [comment]
Alright. Before I merge this pr, have you found out what could be causing the 500 issue on fetching an audiobook? I have the same issue and I could not find anything on the web. If not, I will have to make a thread on their forum i guess.

**Comment by FC5570** [comment]
The push will only trigger when I merge this pr as all your commits will be pushed to main. You can keep it. If the tests does not work after I merge the pr then you can remove it in another.

**Comment by prashanthr** [comment]
> Alright. Before I merge this pr, have you found out what could be causing the 500 issue on fetching an audiobook? I have the same issue and I could not find anything on the web. If not, I will have to make a thread on their forum i guess.

The audiobook issue was a bad id in the [docs reference](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-multiple-audiobooks). I did a live search and fixed the ids [here](https://github.com/spotifyts/spotify.ts/pull/125/commits/1c56f66aedf775a789ec8526d73a0579bb1c34e4). The also passed locally as you can see in the [screenshot here](https://github.com/spotifyts/spotify.ts/pull/125#issuecomment-1291553658).

**Comment by FC5570** [comment]
Alright. I'll merge this one. Lets hope the tests pass.

**Comment by FC5570** [comment]
The tests work. Thanks for your contribution!

**Comment by FC5570** [comment]
@all-contributors please add @prashanthr for code

**Pull request merged**
